version: '3'

services:

  apache:
    image: php:7.2-apache
    volumes:
      - ./src:/var/www/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/logs:/var/log/apache2
      - ./httpd/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      testnet:
        ipv4_address: 192.168.0.10

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - apache
    networks:
      testnet:
        ipv4_address: 192.168.0.20
      

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    volumes:
#      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    networks:
      testnet:
        ipv4_address: 192.168.0.30

  adminer:
    image: adminer
#    restart: always
    links:
      - mysql:db
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      testnet:
        ipv4_address: 192.168.0.40

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
